### ISSUE TITLE
No consensus with 2 nodes only

### ISSUE THREAD

**Issue by DevSidious** [hhblaze/Raft.Net#3]
Based on my understanding ([RAFT consensus](https://www.consul.io/docs/internals/consensus.html)), a RAFT cluster of C(luster)S(ize) = 3 should tolerate the loss of 1 node and still be able to elect a leader.

However, with Raft.NET as soon as the cluster of CS = 3 loses one node (CS = 2) there are no commits until CS is brought back to 3. Basically the absolute minimum of **online nodes** in a cluster must be  3.

Tested in localhost (Windows 10 .Net Core 2.1) as suggested here: [doc](https://docs.google.com/document/d/e/2PACX-1vQYWpDD6L20CSBR4QTlpP2SJDEKcj6VRP-ZI3t_wQ93c3OS96Wk8ojvAFNo3zwYaiz7VUi5EF34JJhZ/pub)

Am I missing something here?

**Comment by hhblaze** [comment]
Will take a look

**Comment by hhblaze** [comment]
Ok, this one works. Currently the quantity of nodes in the cluster is determined by quantity of EndPoint records in config. If you remove 2 endpoints from config, total number of nodes will be 3 and majority will be 2. In current config total is 5 and majority is 3.

**Comment by DevSidious** [comment]
I am able to observe the expected behavior after tweaking the config. Had forgotten that the config has endpoint configuration in it.

Thank you @hhblaze .
