### ISSUE TITLE
Only using in memory entities, still folders are created. 

### ISSUE THREAD

**Issue by Dennis3321** [hhblaze/Raft.Net#4]
Only using in memory entities, still folders are created. 

Well the title says it all, I’m only using in memory entities, but still Raft creates a folder. Judging by the size, Raft does not store anything in it. Most files are 0 bytes, one or two are 72 bytes.

Is there a way to prevent that from happening?

**Comment by hhblaze** [comment]
Hi, can you publish your node config?

**Comment by Dennis3321** [comment]
{
	"RaftEntitiesSettings": [{
		"EntityName": "default",
		"DelayedPersistenceMs": 500,
		"DelayedPersistenceIsActive": false,
		"InMemoryEntity": true,
		"InMemoryEntityStartSyncFromLatestEntity": true,
		"VerboseRaft": false,
		"VerboseTransport": false
	}],
	"TcpClusterEndPoints": [{
			"Host": "127.0.0.1",
			"Port": 4250
		},
		{
			"Host": "127.0.0.1",
			"Port": 4251
		},
		{
			"Host": "127.0.0.1",
			"Port": 4252
		}
	]
}

And then I start with; 

LocalNode = TcpRaftNode.GetFromConfig(RaftConfig, Application.StartupPath & "\dbreeze.db" & My.Settings.localport, My.Settings.localport, log, AddressOf Rafthandler)

**Comment by hhblaze** [comment]
It is not possible, without changing sources, you will have to init Dbreeze different way. Probably the best way is to leave like it is

**Comment by Dennis3321** [comment]
Yea, everything works great. Really beautiful code, every thing works very good, quick. Only problem is, you need a lot of rights to be able to create local folders. For my adaptation that's a problem.

Thanks for the answer.

**Comment by Dennis3321** [comment]
Seems to be working, if I change; 

`Storage = DBreezeConfiguration.eStorage.DISK  ,`

to 

`Storage = DBreezeConfiguration.eStorage.MEMORY ,`

In TCPRaftNode.

Maybe a conditional selection would be nice...

**Comment by Dennis3321** [comment]
`           if (nodeSettings.RaftEntitiesSettings.ElementAt(0).InMemoryEntity == true)
            {
                conf = new DBreezeConfiguration()
                {
                    DBreezeDataFolderName = dbreezePath,
                    Storage = DBreezeConfiguration.eStorage.MEMORY ,
                };
                conf.AlternativeTablesLocations.Add("mem_*", String.Empty);
            } else
            {
                 conf = new DBreezeConfiguration()
                {
                    DBreezeDataFolderName = dbreezePath,
                    Storage = DBreezeConfiguration.eStorage.DISK,
                };
                conf.AlternativeTablesLocations.Add("mem_*", String.Empty);
            }
`

But that's a problem when you have more than one configuration enteties

**Comment by hhblaze** [comment]
Exactly.

**Comment by Dennis3321** [comment]
So this is better;
`            conf = new DBreezeConfiguration(){DBreezeDataFolderName = dbreezePath};
            if (nodeSettings.RaftEntitiesSettings.Where(MyEnt => MyEnt.InMemoryEntity = false).Count() == 0)
            {
                conf.Storage = DBreezeConfiguration.eStorage.MEMORY ;
            } else
            {
                conf.Storage = DBreezeConfiguration.eStorage.DISK ;
            }
            conf.AlternativeTablesLocations.Add("mem_*", String.Empty);
            dbEngine = new DBreezeEngine(conf);`

**Comment by hhblaze** [comment]
Integrated into sources
