### ISSUE TITLE
IsLeader?

### ISSUE THREAD

**Issue by Michael-Kempe** [hhblaze/Raft.Net#7]
Hi,
I'm just curious if there is a way to detect if an instance is running as a Leader? The TCPRaftNode class does not offer such an info?
And by the way.... thanks for sharing this project!

**Comment by hhblaze** [comment]
Hi, wait until Nuget validates version 1.6 and grab it:
raftNodeInstance.IsLeader(optional parameter entityName) will help to understand either node is a Leader or not

**Comment by Michael-Kempe** [comment]
Cool. Thank you!
